/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-pixi-assets. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'virtual:pixi-assets' {
  import type {
    AssetRecordInfo
  } from 'unplugin-pixi-assets/runtime'

  /**
   * Assets list generated by unplugin-pixi-assets. 
   */
  export interface AssetNamedMap {
    "sounds/sound.ogg": AssetRecordInfo<"sounds/sound.ogg", "/src/assets/sounds/sound.ogg", import("@pixi/sound").Sound, import("@pixi/sound").Options>
    "textures/bunny.png": AssetRecordInfo<"textures/bunny.png", "/src/assets/textures/bunny.png", import("pixi.js").Texture,  import("pixi.js").TextureSourceOptions>
  }
}
